[project]
name = "assignment-files"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "flake8>=7.1.1",
    "pytest>=8.3.3",
]
